### ISSUE TITLE
comments not supported properly

### ISSUE THREAD

**Issue by mabaro** [Twinklebear/tobj#13]
Hi,
I am trying out your library (as well as Rust) and just found that there is missing some support for inline comments, like: 
Ka 0.14 0.45 0.091 # Green

I patched my copy of your code as follows, but I think it would be better just to read 3 values and return (error if less than 3 values read):

fn parse_float3(val_str: SplitWhitespace, vals: &mut [f32; 3]) -> bool {
	let mut count : u8 = 0;

    for (i, p) in val_str.enumerate() {
        if p == "#"
        {
            break;
        }
        match FromStr::from_str(p) {
            Ok(x) => { vals[i] = x; count = count+1; },
            Err(_) => return false,
        }
    }
 
	count == 3
}

Cheers,
Marcos

**Comment by Twinklebear** [comment]
Thanks for the bug report @mabaro ! This should be fixed in 6237ed3dec9430fd8449e77108848d15bc07dbc7 , which I'll release as 0.1.9 in just a minute
