### ISSUE TITLE
Add support for n-gons

### ISSUE THREAD

**Issue by virtualritz** [Twinklebear/tobj#22]
Many geometries found in OBJs are _not_ made out of triangles and this is a feature. If I load an OBJ to send to an high end offline renderer, the last thing I want is probably triangles (as such I also do not want the reader to convert the OBJ to triangles, on-the-fly, as tobj does).

Basically the mesh returned would then consist of:
```Rust
mesh.positions
mesh.facevertices // number of vertices per each face (u32)
mesh.indices
```

**Comment by virtualritz** [comment]
I quickly made a file in [Wings3D](https://www.wings3d.com/) – this is an all quad model. Feel free to use however you want.

[knotty02.zip](https://github.com/Twinklebear/tobj/files/4398080/knotty02.zip)

**Comment by Twinklebear** [comment]
Hey @virtualritz , yeah this can be added as an option telling `tobj` not to triangulate. Then it can just give you back the face vertex counts of the quads/polygons directly. Thanks for the test model!

**Comment by virtualritz** [comment]
Yes, this would be super useful.
I am using `tobj` [here (have a play)](https://github.com/virtualritz/rust-diffusion-limited-aggregation).

**Comment by virtualritz** [comment]
Cheers!

**Comment by Twinklebear** [comment]
Should be done in 1ae79e6d1ada57950e4589b32921b28c704e7140 , I'll cut a release shortly. This is a breaking change for the API since I'm just adding a bool option to `load_obj` which will set whether or not to triangulate the loaded faces

**Comment by Twinklebear** [comment]
Let me know if you run into any issues!

**Comment by virtualritz** [comment]
Yeah, cool. I am trying this in a few hours. Will let you know.

**Comment by virtualritz** [comment]
[Done.](https://github.com/virtualritz/rust-diffusion-limited-aggregation/commit/277733d9b683a7a22c861f3d8085bcca78cfc3fc) 

A two line change. Nice one. The commit only looks big because of Rustfmt stuff.

**Comment by virtualritz** [comment]
You should update the README since your crate is actually the only one in the whole Rust universe that doesn't triangulate on import (if not asked to).

**Comment by Twinklebear** [comment]
That's a good point! I'll update it
