### ISSUE TITLE
.positions is generated with repeated vertices.

### ISSUE THREAD

**Issue by Mautar55** [Twinklebear/tobj#31]
To my understanding, positions is a vector which lenght should be the ammount of vertices*3. That doesn't happen with this mesh (attached).
Instead of having 6036 positions, it has 6333. 
The integrity of the file is ok, since blender and online model viewers handle it correctly.
I printed a list and searched the file, some positions are repeated for some reason.

The file contains the model, source code of the program which i used to read it and the list of printed positions.

[issue.zip](https://github.com/Twinklebear/tobj/files/5433278/issue.zip)

**Comment by arrayJY** [comment]
They are not actually "repeated". The same vertex may have different texture coordinates when they sharing by different surfaces. Here is an example.
![image](https://user-images.githubusercontent.com/17538596/108754568-0d577b00-7581-11eb-84b3-9b3f3d4a3972.png)

**Comment by Twinklebear** [comment]
Yeah @arrayJY is right here, this loader will output a unique position for every unique vertex. A unique vertex is every unique combination of position/texcoord/normal . So even if there's only 6036 unique positions in the mesh, there may be more than 6036 unique vertices. To allow referencing each vertex with a single integer index (as in OpenGL, Vulkan, etc.), these re-used positions have to be duplicated. I'd guess that's the case with the suzanne mesh you shared. You could test this in Blender by exporting suzanne without normals and texture coordinates, then you should have `# vertices == # positions` .

**Comment by Mautar55** [comment]
Ok, learned something new then haha. Thanks for the reply.
