### ISSUE TITLE
Documentation does not exists

### ISSUE THREAD

**Issue by Felix7d2** [Twinklebear/tobj#32]
The [Link](https://www.willusher.io/tobj/tobj/) does not work.

**Comment by Twinklebear** [comment]
Thanks for opening this issue, I moved the docs to docs.rs so I don't need to manage building and hosting them anymore: https://docs.rs/tobj/2.0.2/tobj/ . I'll push a patch release crate to update it

**Comment by Twinklebear** [comment]
This is now done in 2.0.3 to fix the link on crates.io
