### ISSUE TITLE
triangulate_faces does not guarantee triangle-only mesh

### ISSUE THREAD

**Issue by virtualritz** [Twinklebear/tobj#36]
I saw this in the docs: 

>  Indices for vertices of each face. If loaded with `triangulate_faces`, each face in the mesh is a triangle, [...]

This is not true. Even with `triangulate_faces` the mesh may still contain (degenerate) faces with two points (type `Line`).
And then the length in the buffer for those is `2`, not `3`.
So that the indices for face `n` in the buffer do *not* start at `n * 3` in this case.

I suggest blowing up such faces into degenerate triangles when `triangulate_faces` is on and making the resp. index in an `Option`. I will include this change in my fork so you can have a look.

**Comment by Twinklebear** [comment]
This is part of the PR and now in 3.0.0 correct? So we can close this?

**Comment by virtualritz** [comment]
Correct.
