### ISSUE TITLE
Add support for merging disconnected vertices w. matching positions on import

### ISSUE THREAD

**Issue by virtualritz** [Twinklebear/tobj#41]
[I think I have this working for `positions` & `indices`](https://github.com/virtualritz/tobj/blob/reordering/src/lib.rs#L1280-L1319). Possibly should also do the same for `normals`/`texcoords` and the resp. index buffers.

But would be good to get feedback before I create a PR. It's in my [reordering branch](https://github.com/virtualritz/tobj/tree/reordering) which has two new feature flags, `reordering` and `merging` to ensure dependencies & compile time stay the same for users of the crate who don't need these features.

**Comment by virtualritz** [comment]
I added support for merging of normal & texcoord indices too now. To avoid code duplication, the code uses const generics. This means the `reordering` branch will only build with a `beta` toolchain atm.

This could be changed by copypastaing the code for the textcoord case ofc.

**Comment by Twinklebear** [comment]
This is part of the PR and now in 3.0.0 correct? So we can close this
